#!/usr/bin/env bash
set -e

SCRIPTS_DIR="$(readlink -f "$(dirname "$0")")/.."

# shellcheck source=build/scripts/common.sh
. "${SCRIPTS_DIR}"/common.sh

# Build the runner image
pushd "${SCRIPTS_DIR}/../uci-build"
docker build -t uci-runner .
