#!/usr/bin/env bash
set -e

SCRIPTS_DIR="$(readlink -f "$(dirname "$0")")/.."

# shellcheck source=build/scripts/common.sh
. "${SCRIPTS_DIR}"/common.sh
parse_env_args

cd "${BUILDDIR}"
"${SCRIPTS_DIR}/core/run" /usr/bin/env bash -c 'sccache --start-server && sleep 3 && sccache --show-stats'
