#!/usr/bin/env bash
set -e

SCRIPTS_DIR="$(readlink -f "$(dirname "$0")")/.."

# shellcheck source=build/scripts/common.sh
. "${SCRIPTS_DIR}"/common.sh
parse_env_args

cd "${BUILDDIR}"
"${SCRIPTS_DIR}/core/run" ./staging_dir/host/bin/ccache -vs -d /ccache-storage --clear
