#!/usr/bin/env bash
set -euo pipefail

# Unpack two images and run diff on them

SCRIPTS_DIR="$(readlink -f "$(dirname "$0")")/.."

# shellcheck source=build/scripts/common.sh
. "${SCRIPTS_DIR}"/common.sh
parse_env_args

source_device_lib

# shellcheck source=build/scripts/libs/diff-images-runner
. "${SCRIPTS_DIR}/libs/diff-images-runner.sh"
