#!/usr/bin/env bash
set -euo pipefail

# Enter the shell in a build environment

SCRIPTS_DIR="$(readlink -f "$(dirname "$0")")/.."
# shellcheck source=build/scripts/common.sh
. "${SCRIPTS_DIR}"/common.sh

echoerr "Build docker build environment image (development)"
DOCKER_BUILD_DEV_IMAGE=true "${SCRIPTS_DIR}/core/setup-image"

# shellcheck disable=SC2086,SC2016,SC2097,SC2098
CUR_DIR="$PWD" SCRIPTS_DIR="$SCRIPTS_DIR" DOCKER_IMAGE=openwrt-builder-dev INTERACTIVE_USAGE=true ${SCRIPTS_DIR}/core/run bash -c '\
    cd ${CUR_DIR} && \
    . ${SCRIPTS_DIR}/common.sh && \
    parse_env_args && \
    bash'
