#!/usr/bin/env bash

# This script performs end-to-end testing for out-of-tree scenario.
# This includes cloning repo, fetching packages, templating files and the build itself
# It's meant to be used when major changes are introduced to the directory layout

[ -z "$OOT_TEST_DIR" ] && echo "OOT_TEST_DIR variable must be set" && exit 1

ROOT_DIR="$(readlink -f "$(dirname "$0")")/.."
pushd "$ROOT_DIR" || exit 1

# Copy required parts of the repo
mkdir -p "$OOT_TEST_DIR/openwrt_build_wrapper"

readarray -t directories_to_copy < <(git ls-tree -r HEAD --name-only | cut -d "/" -f1 | sort | uniq)

cp -ra "${directories_to_copy[@]}" .git "$OOT_TEST_DIR/openwrt_build_wrapper"

cp -ra config "$OOT_TEST_DIR"

pushd "$OOT_TEST_DIR" || exit 1

export DEVICE=example

time ONLY_INITIALIZE_WORKSPACE=true ./openwrt_build_wrapper/scripts/core/entrypoint
time SKIP_DOWNLOADS=true ./openwrt_build_wrapper/scripts/core/entrypoint
