#!/usr/bin/env bash
set -e

# Clone with full history to have git log in place

SCRIPTS_DIR="$(readlink -f "$(dirname "$0")")/.."

# shellcheck source=build/scripts/common.sh
. "${SCRIPTS_DIR}"/common.sh
parse_env_args

if [[ ! -d "${BUILDDIR}" ]]; then
	git clone git://git.openwrt.org/openwrt/openwrt.git "${BUILDDIR}"
else
	while true; do
		read -rp "There is already an openwrt dir, do you wish to use it? [Y/N]" yn
		case $yn in
		[Yy]*) break ;;
		[Nn]*)
			echo "Please remove it manually to avoid loss of work"
			exit 1
			;;
		*) echo "Please answer yes or no." ;;
		esac
	done
fi

cd "${BUILDDIR}"

git checkout "${OPENWRT_VERSION}"
