#!/usr/bin/env bash
set -e

SCRIPTS_DIR="$(readlink -f "$(dirname "$0")")/.."

# shellcheck source=build/scripts/common.sh
. "${SCRIPTS_DIR}/common.sh"

cd "${SCRIPTS_DIR}/../docker-setup/"
docker build -t openwrt-builder .

if [[ "${DOCKER_BUILD_DEV_IMAGE:-}" == "true" ]]; then
	docker build -t openwrt-builder-dev -f Dockerfile.dev .
fi
