$script_init = <<-SCRIPT
set -e
# I just want the internet!
sed -i 's#nameserver.*#nameserver 8.8.8.8##' /etc/resolv.conf

apt-get update && \
apt-get upgrade -y
SCRIPT

$script = <<-SCRIPT
apt-get install -y git docker.io
sudo usermod -aG docker vagrant
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = 'generic/ubuntu2204'

  if Vagrant.has_plugin?("vagrant-disksize")
    config.disksize.size = '200GB'
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 16384
    v.cpus = 10
  end

  config.vm.provider "libvirt" do |v|
    v.memory = 16384
    v.cpus = 10
  end

  config.vm.synced_folder '.', '/vagrant', disabled: true
  #config.vm.synced_folder '../../', '/home/vagrant/network_layout'

  config.vm.provision "shell", inline: $script_init
  config.vm.provision "shell", reboot: true
  config.vm.provision "shell", inline: $script
  config.vm.provision "shell", reboot: true
end
